services:

  app:
      build: .
      env_file: .env
      ports:
        - "8000:8000"
      #      - "5678:5678"
      depends_on:
        - db
      restart: always
      networks:
        - postgres

  db:
    image: postgres:latest
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_HOST: ${POSTGRES_HOST}
    ports:
      - "5433:5432"

    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: always

    networks:
      - postgres

  pgadmin:
    container_name: pgadmin_container
    image: dpage/pgadmin4:latest

    depends_on:
      - db

    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL:-pgadmin@example.com}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD:-admin}
      PGADMIN_CONFIG_SERVER_MODE: 'False'

    volumes:
      - pgadmin_data:/var/lib/pgadmin

    ports:
      - ${PGADMIN_PORT:-5050}:80

    networks:
      - postgres


    restart: unless-stopped


networks:
  postgres:
    driver: bridge

volumes:
  postgres_data:
  pgadmin_data:
